/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/asset.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/node1.ts" />
/// <reference path="../scenes/node2.ts" />
/// <reference path="../scenes/node3.ts" />
/// <reference path="../scenes/node4.ts" />
/// <reference path="../scenes/node5.ts" />
/// <reference path="../scenes/node6.ts" />
/// <reference path="../scenes/node7.ts" />
/// <reference path="../scenes/node8.ts" />
/// <reference path="../scenes/node9.ts" />
/// <reference path="../scenes/node10.ts" />
/// <reference path="../scenes/node11.ts" />
/// <reference path="../scenes/node12.ts" />
/// <reference path="../scenes/node13.ts" />
/// <reference path="../scenes/node14.ts" />
/// <reference path="../scenes/node15.ts" />
/// <reference path="../scenes/game.ts" />
/// <reference path="../scenes/gameover.ts" /> 
//# sourceMappingURL=_reference.js.map